#!/bin/sh
### BEGIN INIT INFO
# Provides:	     socat
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Screen to tcp232
# Description:       This script create virtual tty over tcp (connect to USR-tcp232-2) and create detach screen with logging to this tty.
### END INIT INFO

# Author: Nikita Shchipachev <shchipachevnm@gmail.com>

IP=192.168.42.3
PORT=20108
TTY=/dev/tty.lab.kem.q2p.us

RETVAL=0

case "$1" in
start)
test -c $TTY || ( socat PTY,link=$TTY,raw,mode=666,echo=0 TCP:$IP:$PORT & sleep 1 )
screen -list | grep -q ttyS0 || screen -d -m -S ttyS0 -L $TTY
RETVAL=$?
;;
stop)
ps w | grep "socat PTY,link=$TTY,raw,mode=666,echo=0 TCP:$IP:$PORT" | grep -q -v grep && kill `ps w | grep "socat PTY,link=$TTY,raw,mode=666,echo=0 TCP:$IP:$PORT" | grep -v grep | awk '{print $1}'` || echo "already killed"
RETVAL=$?
;;
restart)
ps w | grep "socat PTY,link=$TTY,raw,mode=666,echo=0 TCP:$IP:$PORT" | grep -q -v grep && kill `ps w | grep "socat PTY,link=$TTY,raw,mode=666,echo=0 TCP:$IP:$PORT" | grep -v grep | awk '{print $1}'`
sleep 1
test -c $TTY || ( socat PTY,link=$TTY,raw,mode=666,echo=0 TCP:$IP:$PORT & sleep 1 )
screen -list | grep -q ttyS0 || screen -d -m -S ttyS0 -L $TTY
RETVAL=$?
;;
status)
ps w | grep "socat PTY,link=$TTY,raw,mode=666,echo=0 TCP:$IP:$PORT" | grep -v grep
screen -list
RETVAL=$?
;;
*)
echo "Usage: tcp232 {start|stop|restart|status}"
exit 1
;;
esac
exit $RETVAL
